export type Option = { id: string; en: string; ar: string };

export const saudiCities: Option[] = [
  ["jeddah","Jeddah","جدة"],["riyadh","Riyadh","الرياض"],["dammam","Dammam","الدمام"],["khobar","Al Khobar","الخبر"],["makkah","Makkah","مكة المكرمة"],["madinah","Madinah","المدينة المنورة"],["taif","Taif","الطائف"],["jubail","Jubail","الجبيل"],["yanbu","Yanbu","ينبع"],["abha","Abha","أبها"],["tabuk","Tabuk","تبوك"],["hail","Hail","حائل"],["buraidah","Buraidah","بريدة"],["unaizah","Unaizah","عنيزة"],["al-ahsa","Al Ahsa","الأحساء"],["qatif","Qatif","القطيف"],["najran","Najran","نجران"],["jazan","Jazan","جازان"],["khamis-mushait","Khamis Mushait","خميس مشيط"],["sakaka","Sakaka","سكاكا"],["arar","Arar","عرعر"],["al-bahah","Al Bahah","الباحة"],["ras-tanura","Ras Tanura","رأس تنورة"],["anywhere","Anywhere in Saudi Arabia","أي مكان في السعودية"]
].map(([id,en,ar]) => ({ id,en,ar }));

export const saudiIndustries: Option[] = [
  ["technology","Technology & Software","التقنية والبرمجيات"],["data","Data, AI & Analytics","البيانات والذكاء الاصطناعي والتحليلات"],["cybersecurity","Cybersecurity","الأمن السيبراني"],["cloud","Cloud & Infrastructure","الحوسبة السحابية والبنية التحتية"],["telecom","Telecommunications","الاتصالات"],["finance","Finance & Banking","المالية والمصارف"],["insurance","Insurance","التأمين"],["fintech","FinTech","التقنية المالية"],["accounting","Accounting & Audit","المحاسبة والمراجعة"],["healthcare","Healthcare & Hospitals","الرعاية الصحية والمستشفيات"],["pharma","Pharmaceuticals & Life Sciences","الأدوية وعلوم الحياة"],["education","Education & Training","التعليم والتدريب"],["engineering","Engineering","الهندسة"],["construction","Construction & Real Estate","الإنشاءات والعقارات"],["energy","Energy, Oil & Gas","الطاقة والنفط والغاز"],["utilities","Utilities & Sustainability","المرافق والاستدامة"],["manufacturing","Manufacturing & Industrial","التصنيع والصناعة"],["automotive","Automotive","السيارات"],["logistics","Logistics & Supply Chain","الخدمات اللوجستية وسلاسل الإمداد"],["aviation","Aviation & Airports","الطيران والمطارات"],["maritime","Maritime & Ports","القطاع البحري والموانئ"],["retail","Retail & E-commerce","التجزئة والتجارة الإلكترونية"],["sales","Sales & Business Development","المبيعات وتطوير الأعمال"],["marketing","Marketing, PR & Communications","التسويق والعلاقات العامة والاتصال"],["media","Media, Content & Design","الإعلام والمحتوى والتصميم"],["hospitality","Hospitality & Tourism","الضيافة والسياحة"],["events","Events & Entertainment","الفعاليات والترفيه"],["hr","Human Resources & Recruitment","الموارد البشرية والتوظيف"],["legal","Legal & Compliance","الشؤون القانونية والامتثال"],["government","Government & Public Sector","القطاع الحكومي والعام"],["nonprofit","Nonprofit & Social Impact","القطاع غير الربحي والأثر الاجتماعي"],["security","Security & Facilities","الأمن وإدارة المرافق"],["agriculture","Agriculture & Food Production","الزراعة والإنتاج الغذائي"],["food","Food & Beverage","الأغذية والمشروبات"],["fashion","Fashion & Beauty","الأزياء والجمال"],["consulting","Consulting & Professional Services","الاستشارات والخدمات المهنية"],["research","Research & Development","البحث والتطوير"],["sports","Sports & Wellness","الرياضة والعافية"]
].map(([id,en,ar]) => ({ id,en,ar }));
