import { useState } from "react";
import { Link } from "wouter";
import { Download, FileText, Loader2, Sparkles } from "lucide-react";
import { trpc } from "@/lib/trpc";

export default function Ats() {
  const [text, setText] = useState(""); const [file, setFile] = useState(""); const [role, setRole] = useState("");
  const analyze = trpc.campaign.ats.analyze.useMutation();
  const choose = async (f?: File) => { if (!f) return; const { readCvText } = await import("@/lib/careerMatcher"); setFile(f.name); setText(await readCvText(f)); };
  const exportResult = () => { if (!analyze.data) return; const blob = new Blob([`AutoApply SA ATS review\n\nScore: ${analyze.data.score}/100\n\n${analyze.data.summary}\n\nStrengths\n${analyze.data.strengths.map(x=>`- ${x}`).join("\n")}\n\nPriority improvements\n${analyze.data.gaps.map(x=>`- ${x}`).join("\n")}\n\nOptimized CV bullets\n${analyze.data.optimizedBullets.map(x=>`- ${x}`).join("\n")}\n\n${analyze.data.disclaimer}`], { type: "text/plain" }); const a=document.createElement("a"); a.href=URL.createObjectURL(blob); a.download="autoapply-sa-ats-review.txt"; a.click(); URL.revokeObjectURL(a.href); };
  return <main className="min-h-screen bg-[#f3f0e9] text-[#151515] p-6 md:p-12"><div className="max-w-3xl mx-auto space-y-7"><Link href="/" className="font-mono text-xs">← BACK TO AUTOAPPLY SA</Link><header><p className="font-mono text-xs text-[#e5482a]">AI ATS REVIEW / SAUDI ARABIA</p><h1 className="text-4xl font-bold mt-3">Make your CV easier to read, <i>not fictional.</i></h1><p className="mt-3 text-[#151515]/70">Your file is read in this browser. Only extracted text is sent when you start the AI review; the file itself is not uploaded.</p></header><section className="bg-white border border-black/10 p-6 space-y-4"><label className="block border-2 border-dashed border-black/20 p-5 cursor-pointer"><input className="sr-only" type="file" accept=".pdf,.docx,.txt" onChange={e=>choose(e.target.files?.[0])}/><FileText className="inline mr-2"/> <b>{file || "Choose a PDF, DOCX, or TXT CV"}</b></label><input className="w-full border border-black/20 p-3" value={role} onChange={e=>setRole(e.target.value)} placeholder="Target role (optional)"/><textarea className="w-full min-h-40 border border-black/20 p-3" value={text} onChange={e=>setText(e.target.value)} placeholder="CV text appears here after local extraction."/><button disabled={text.length<120 || analyze.isPending} onClick={()=>analyze.mutate({cvText:text,targetRole:role||undefined})} className="bg-[#151515] text-white px-5 py-3 disabled:opacity-50">{analyze.isPending ? <><Loader2 className="inline animate-spin mr-2"/>Analysing CV signals…</> : <><Sparkles className="inline mr-2"/>Run AI ATS review</>}</button>{analyze.isPending && <p role="status" className="text-sm">Checking structure, keywords, and evidence. This usually takes a moment.</p>}</section>{analyze.data && <section className="bg-[#151515] text-white p-6 space-y-4"><div className="flex justify-between"><h2 className="text-2xl">ATS readiness: {analyze.data.score}/100</h2><button onClick={exportResult} className="border px-3 py-2"><Download className="inline mr-1"/>Export</button></div><p>{analyze.data.summary}</p><h3>Strengths</h3><ul>{analyze.data.strengths.map(x=><li key={x}>• {x}</li>)}</ul><h3>Priority improvements</h3><ul>{analyze.data.gaps.map(x=><li key={x}>• {x}</li>)}</ul><h3>Suggested bullets</h3><ul>{analyze.data.optimizedBullets.map(x=><li key={x}>• {x}</li>)}</ul><small>{analyze.data.disclaimer}</small></section>}{analyze.error && <p role="alert">Unable to complete the review. Please try again.</p>}</div></main>;
}
