import { readFileSync } from "node:fs";
import { resolve } from "node:path";
import { describe, expect, it } from "vitest";

const homeSource = () => readFileSync(resolve(process.cwd(), "client/src/pages/Home.tsx"), "utf8");
const arabicHomeSource = () => readFileSync(resolve(process.cwd(), "client/src/pages/ArabicHome.tsx"), "utf8");
const stylesSource = () => readFileSync(resolve(process.cwd(), "client/src/index.css"), "utf8");

describe("homepage clarity release", () => {
  it("states the service plainly and keeps the approved campaign CTA paths", () => {
    const source = homeSource();

    expect(source).toContain("We apply to jobs for you.");
    expect(source).toContain("AutoApply SA submits tailored job applications to Saudi companies on your behalf");
    expect(source).toContain('href="/enquire"');
    expect(source).toContain("https://wa.me/966571448656");
  });

  it("keeps one how-it-works section and removes duplicate explainers", () => {
    const source = homeSource();

    expect(source).toContain('id="how"');
    expect(source).not.toContain("APPLICATION INFRASTRUCTURE");
    expect(source).not.toContain("WHAT THE SERVICE DOES");
    expect(source).not.toContain("PROCESS CASE STUDY");
  });

  it("includes the video-ready placeholder and does not promise a copilot", () => {
    const source = homeSource();

    expect(source).toContain("30 seconds. That&apos;s all it takes to understand.");
    expect(source).toContain("Video loading — generated by AutoApply SA");
    expect(source).toContain("autoPlay loop muted playsInline");
    expect(source).toContain("Priority human review");
    expect(source).not.toContain("Julie copilot");
  });

  it("keeps the Arabic hero plain-language and removes matching duplicate rendered sections", () => {
    const source = arabicHomeSource();

    expect(source).toContain("نتقدّم للوظائف");
    expect(source).toContain("سيرتك الذاتية جاهزة");
    expect(source).toContain("arabic-video-explainer-heading");
    expect(source).not.toContain("البنية التحتية للتقديم");
    expect(source).not.toContain("ما تقدّمه الخدمة");
    expect(source).not.toContain("هذا المثال التوضيحي يشرح كيف تنتقل الحملة");
    expect(stylesSource()).toContain("جرّبها الآن — تستغرق 60 ثانية");
    expect(stylesSource()).toContain("أضف سيرتك الذاتية. سنوضح لك ما تستطيع فعله.");
  });
});
