import { useEffect } from "react";
import { applyPageSeo } from "@/lib/seo";
import { InformationPageLayout } from "@/components/InformationPageLayout";

type PageKind = "how" | "support" | "privacy" | "terms" | "case" | "sample";
type Section = { heading: string; detail: string };
type PageCopy = { kicker: string; title: string; intro: string; reviewNote?: string; sections: Section[] };

const copy: Record<"en" | "ar", Record<PageKind, PageCopy>> = {
  en: {
    how: { kicker: "HOW AUTOAPPLY SA WORKS", title: "A clear system for a Saudi job search.", intro: "Review your CV, set Saudi role targets, confirm your campaign direction, and track applications in your dashboard. Nothing is submitted from this page without your confirmation.", sections: [{ heading: "1. Set your direction", detail: "Choose Saudi cities, industries, language and role priorities." }, { heading: "2. Review the match", detail: "Use the local CV check and AI ATS review to improve clarity before sharing a campaign brief." }, { heading: "3. Confirm your campaign", detail: "WhatsApp opens with a prefilled summary so you decide what to send and attach." }, { heading: "4. Track progress", detail: "Signed-in candidates can review their own submitted applications in the dashboard." }] },
    support: { kicker: "SUPPORT", title: "Help, without a ticket maze.", intro: "Get help with your AutoApply SA campaign, dashboard access, or privacy requests for your Saudi Arabia job search.", sections: [{ heading: "Campaign support", detail: "Use WhatsApp for the quickest conversation about a role target, CV attachment, or campaign status." }, { heading: "Dashboard access", detail: "Sign in with the same account used for your candidate profile to view your personal application feed." }, { heading: "Privacy request", detail: "Ask to access or remove campaign information by sending a clear request with your email address." }, { heading: "Response expectation", detail: "If you do not receive a reply within one business day, send a concise WhatsApp follow-up." }] },
    privacy: { kicker: "PRIVACY POLICY", title: "Purposeful handling for your career information.", intro: "This working privacy-policy draft explains how AutoApply SA handles personal data in its Saudi-focused job-application service.", reviewNote: "Working draft — review with a qualified Saudi privacy professional before relying on it.", sections: [{ heading: "Who is responsible", detail: "AutoApply SA, operating from Jeddah, is responsible for the purposes and manner of processing information shared through this site and during an agreed campaign." }, { heading: "Information we may collect", detail: "This can include contact details, CV text or documents you choose to share, target-role and location preferences, application and campaign history, correspondence, and technical consent preferences. We do not collect more information than is relevant to the requested service." }, { heading: "Why we use it", detail: "We use information to respond to enquiries, discuss or operate an agreed job-application campaign, maintain your candidate dashboard, protect the service, and meet applicable legal obligations. Consent may be requested for optional analytics and for processing that requires it; other processing may be necessary to take steps you request or to pursue legitimate service interests where permitted." }, { heading: "How information is stored and shared", detail: "Preview matching runs in the browser as described on the site. Information you actively share may be handled through approved service providers and channels needed to operate the service, such as hosting, authenticated dashboard, email, WhatsApp, or application platforms. We do not sell CVs or application history as a separate product." }, { heading: "Retention and security", detail: "We keep identifiable information only for as long as needed for the stated purpose, an active campaign, a legal requirement, or a documented dispute. We apply organisational, administrative, and technical safeguards appropriate to the service, then securely delete or anonymise information when it is no longer needed." }, { heading: "Your rights and contact", detail: "Subject to applicable law, you may request information about processing, access to your data, correction, a readable copy, destruction when no longer needed, or withdrawal of consent. Send a clear request with the email used for your campaign to hasan@hsndm.tech or use the published WhatsApp channel. We may need to verify your identity before acting." }, { heading: "Cookies and optional analytics", detail: "Necessary storage records your privacy choice. Optional site analytics remains disabled unless you choose to allow it in the consent notice. You can reopen Cookie settings from the site at any time." }] },
    terms: { kicker: "TERMS & CONDITIONS", title: "Clear boundaries for an application campaign.", intro: "These working terms describe the AutoApply SA website, preview tools, and agreed campaign service. They do not replace a separate written campaign quotation or agreement.", reviewNote: "Working draft — review with a qualified Saudi legal professional before relying on it.", sections: [{ heading: "Service scope", detail: "AutoApply SA may provide career-support, role-matching, campaign discussion, and, where separately agreed, job-application support for opportunities in Saudi Arabia. The preview tools do not themselves submit applications." }, { heading: "No placement guarantee", detail: "Role matches, ATS feedback, and campaign activity are guidance and operational support. They do not guarantee an interview, offer, response, placement, salary outcome, or a particular application volume." }, { heading: "Your responsibilities", detail: "You are responsible for the accuracy, completeness, and lawfulness of the CV, contact details, preferences, and other material you provide. You must review and confirm any campaign direction before applications are sent on your behalf." }, { heading: "Fees, cancellation, and refunds", detail: "No payment is collected through this website. Where a paid campaign is agreed, the applicable price in SAR, scope, start date, cancellation terms, and any refund position must be confirmed in the written quotation or agreement for that campaign before payment or work begins." }, { heading: "Acceptable use and dashboards", detail: "Do not misuse the site, impersonate another person, attempt unauthorised access, or share dashboard access credentials. Candidate dashboards are intended only for the relevant signed-in candidate and authorised support activity." }, { heading: "Changes and contact", detail: "We may update these terms as the service develops. Material service commitments for an active paid campaign should be confirmed in writing. Questions can be sent to hasan@hsndm.tech or through the published WhatsApp channel." }] },
    case: { kicker: "CASE STUDY / OPERATIONS", title: "KAIA Terminal 1: finding flow friction before it becomes a queue.", intro: "A working case-study summary for an operations-improvement project using DMAIC and value-stream mapping at King Abdulaziz International Airport Terminal 1.", reviewNote: "Case-study draft — the figures below were supplied by the site owner and should be supported by approved project evidence before external reliance.", sections: [{ heading: "Operational context", detail: "The project examined passenger-flow and service-process friction in the Terminal 1 environment, with a focus on identifying delay points that affect queue movement and staff time." }, { heading: "Method", detail: "The work applied DMAIC discipline and value-stream mapping to define the operating problem, identify handoffs and bottlenecks, measure the current flow, and frame targeted improvement opportunities." }, { heading: "Owner-reported outcome", detail: "The owner reports a 41% reduction in process time and a 50% decrease in queue volume for the studied workflow. These are project-specific figures, not a promise of a repeatable result." }, { heading: "What transfers", detail: "The relevant lesson for automation work is to make invisible handoffs visible, constrain the flow to only necessary steps, and measure outcomes before expanding a process." }] },
    sample: { kicker: "ILLUSTRATIVE DELIVERABLE", title: "What a campaign update is designed to show.", intro: "This is an illustrative weekly-report format, not a live campaign record and not a promise of a particular volume, result, or employer response.", reviewNote: "Illustrative only — no candidate, employer, role, application, or result shown here is live campaign data.", sections: [{ heading: "Delivery rhythm", detail: "A written campaign plan should state the agreed reporting cadence, such as a weekly update, and the contact route for questions or pause requests." }, { heading: "Application log fields", detail: "Where an application is actually submitted, the candidate-facing log is designed to show employer, role, channel, submitted date, and current status. It should distinguish submitted, queued, skipped, and any response received." }, { heading: "What the report does not prove", detail: "A report does not guarantee that a role remains open, an employer reviewed an application, or an interview or offer will follow. Status reflects the evidence available at the time of the update." }, { heading: "Preview versus live campaign", detail: "The website’s readiness tools and examples are previews. A live campaign begins only after a separate written plan identifies approved role families, locations, channels, maximum volume, timing, and a candidate authorization." }] },
  },
  ar: {
    how: { kicker: "كيف تعمل أوتوأبلاي السعودية", title: "نظام واضح لبحثك عن عمل داخل السعودية.", intro: "راجع سيرتك، وحدّد أدوارك المستهدفة داخل السعودية، واعتمد اتجاه الحملة، ثم تابع الطلبات في لوحتك. لا يُرسل أي طلب من هذه الصفحة دون تأكيدك.", sections: [{ heading: "1. حدّد اتجاهك", detail: "اختر المدن السعودية والمجالات واللغة وأولوية الوظيفة." }, { heading: "2. راجع المطابقة", detail: "استخدم فحص السيرة المحلي ومراجعة ATS لتحسين الوضوح قبل مشاركة ملخص الحملة." }, { heading: "3. أكّد حملتك", detail: "يفتح WhatsApp بملخص جاهز لتقرر أنت ما الذي سترسله وما الذي سترفقه." }, { heading: "4. تابع التقدم", detail: "يمكن للمرشحين المسجلين مراجعة طلباتهم الخاصة داخل لوحة التحكم." }] },
    support: { kicker: "الدعم", title: "مساعدة واضحة بلا تعقيد.", intro: "احصل على المساعدة في حملة AutoApply SA أو دخول لوحة المرشح أو طلبات الخصوصية للبحث عن عمل داخل السعودية.", sections: [{ heading: "دعم الحملة", detail: "استخدم WhatsApp لبدء محادثة سريعة حول الوظيفة المستهدفة أو السيرة أو حالة الحملة." }, { heading: "الوصول إلى اللوحة", detail: "سجّل الدخول بالحساب نفسه المستخدم في ملفك لمراجعة تغذية طلباتك الشخصية." }, { heading: "طلب الخصوصية", detail: "اطلب الوصول إلى معلومات حملتك أو حذفها بإرسال طلب واضح يتضمن بريدك الإلكتروني." }, { heading: "توقع الرد", detail: "إذا لم يصلك رد خلال يوم عمل واحد، أرسل متابعة مختصرة عبر WhatsApp." }] },
    privacy: { kicker: "سياسة الخصوصية", title: "تعامل هادف مع معلوماتك المهنية.", intro: "تشرح هذه المسودة العملية لسياسة الخصوصية كيفية تعامل AutoApply SA مع البيانات الشخصية ضمن خدمة التقديم على الوظائف الموجّهة للسعودية.", reviewNote: "مسودة عمل — يُرجى مراجعتها مع مختص سعودي مؤهل في الخصوصية قبل الاعتماد عليها.", sections: [{ heading: "الجهة المسؤولة", detail: "تتحمل AutoApply SA، ومقرّها جدة، مسؤولية تحديد أغراض ووسائل معالجة المعلومات التي تشاركها عبر الموقع وخلال الحملة المتفق عليها." }, { heading: "المعلومات التي قد نجمعها", detail: "قد تشمل بيانات الاتصال، نص السيرة الذاتية أو مستنداتها التي تختار مشاركتها، وتفضيلات الوظائف والمواقع، وسجل الطلبات والحملة، والمراسلات، وتفضيلات الموافقة التقنية. ولا نجمع أكثر مما يلزم للخدمة المطلوبة." }, { heading: "سبب استخدامنا للمعلومات", detail: "نستخدم المعلومات للرد على الاستفسارات، ومناقشة أو تشغيل حملة تقديم متفق عليها، وإدارة لوحة المرشح، وحماية الخدمة، والوفاء بالالتزامات النظامية. وقد نطلب الموافقة للتحليلات الاختيارية أو المعالجة التي تتطلبها؛ وقد تكون معالجة أخرى لازمة لاتخاذ خطوات تطلبها أو لمصالح مشروعة للخدمة حيث يسمح النظام." }, { heading: "التخزين والمشاركة", detail: "تعمل المطابقة التجريبية محلياً في المتصفح كما يوضح الموقع. وقد تُعالج المعلومات التي تشاركها فعلياً عبر مزودي خدمات وقنوات معتمدة لازمة لتشغيل الخدمة، مثل الاستضافة واللوحة الموثقة والبريد وWhatsApp ومنصات التقديم. ولا نبيع السير الذاتية أو سجل الطلبات كمنتج مستقل." }, { heading: "الاحتفاظ والأمان", detail: "نحتفظ بالمعلومات القابلة للتعريف فقط للمدة اللازمة للغرض المعلن أو للحملة النشطة أو لمتطلب نظامي أو نزاع موثق. ونطبق ضمانات تنظيمية وإدارية وتقنية مناسبة للخدمة، ثم نحذف المعلومات بأمان أو نُخفي هويتها عند انتهاء الحاجة إليها." }, { heading: "حقوقك والتواصل", detail: "وفقاً للنظام المعمول به، يمكنك طلب معرفة كيفية المعالجة، والوصول إلى بياناتك، وتصحيحها، والحصول على نسخة مقروءة، وطلب إتلافها عند عدم الحاجة، أو سحب الموافقة. أرسل طلباً واضحاً مع البريد المستخدم في الحملة إلى hasan@hsndm.tech أو عبر قناة WhatsApp المنشورة. وقد نحتاج للتحقق من هويتك قبل التنفيذ." }, { heading: "ملفات الارتباط والتحليلات الاختيارية", detail: "يُستخدم التخزين الضروري لتسجيل اختيارك للخصوصية. وتبقى تحليلات الموقع الاختيارية معطّلة ما لم تسمح بها عبر إشعار الموافقة. ويمكنك إعادة فتح إعدادات ملفات الارتباط من الموقع في أي وقت." }] },
    terms: { kicker: "الشروط والأحكام", title: "حدود واضحة لحملة التقديم.", intro: "توضح هذه المسودة شروط موقع AutoApply SA وأدوات المعاينة وخدمة الحملة المتفق عليها. ولا تحل محل عرض سعر أو اتفاق حملة مكتوب منفصل.", reviewNote: "مسودة عمل — يُرجى مراجعتها مع مختص قانوني سعودي مؤهل قبل الاعتماد عليها.", sections: [{ heading: "نطاق الخدمة", detail: "قد تقدم AutoApply SA دعماً مهنياً ومطابقة وظائف ومناقشة الحملة، وعند الاتفاق المنفصل دعم التقديم على الوظائف داخل السعودية. ولا تُرسل أدوات المعاينة طلبات تقديم بنفسها." }, { heading: "لا ضمان للتوظيف", detail: "نتائج المطابقة وملاحظات ATS ونشاط الحملة هي إرشاد ودعم تشغيلي، ولا تضمن مقابلة أو عرضاً أو رداً أو توظيفاً أو راتباً أو حجماً محدداً من الطلبات." }, { heading: "مسؤولياتك", detail: "أنت مسؤول عن دقة واكتمال ومشروعية السيرة الذاتية وبيانات الاتصال والتفضيلات والمواد الأخرى التي تقدمها. ويجب عليك مراجعة اتجاه الحملة وتأكيده قبل إرسال أي طلبات بالنيابة عنك." }, { heading: "الرسوم والإلغاء والاسترداد", detail: "لا يجمع هذا الموقع مدفوعات. وعند الاتفاق على حملة مدفوعة، يجب تأكيد السعر بالريال السعودي والنطاق وتاريخ البدء وشروط الإلغاء وأي موقف للاسترداد في عرض السعر أو الاتفاق المكتوب الخاص بالحملة قبل الدفع أو بدء العمل." }, { heading: "الاستخدام المقبول واللوحات", detail: "لا تُسئ استخدام الموقع أو تنتحل شخصية غيرك أو تحاول الوصول غير المصرح به أو تشارك بيانات دخول اللوحة. ولوحة المرشح مخصصة للمرشح المسجل المعني ولأنشطة الدعم المصرح بها." }, { heading: "التغييرات والتواصل", detail: "قد نحدّث هذه الشروط مع تطور الخدمة. وينبغي تأكيد الالتزامات الجوهرية للحملة المدفوعة النشطة كتابةً. ويمكن إرسال الأسئلة إلى hasan@hsndm.tech أو عبر قناة WhatsApp المنشورة." }] },
    case: { kicker: "دراسة حالة / عمليات", title: "مبنى الركاب 1 في مطار الملك عبدالعزيز: كشف عوائق التدفق قبل أن تتحول إلى طوابير.", intro: "ملخص عملي لدراسة حالة في تحسين العمليات باستخدام DMAIC ورسم تدفق القيمة في مبنى الركاب 1 بمطار الملك عبدالعزيز الدولي.", reviewNote: "مسودة دراسة حالة — زوّد مالك الموقع الأرقام أدناه، وينبغي دعمها بأدلة مشروع معتمدة قبل الاعتماد الخارجي عليها.", sections: [{ heading: "السياق التشغيلي", detail: "درست المبادرة عوائق تدفق المسافرين والعمليات الخدمية في بيئة مبنى الركاب 1، مع التركيز على نقاط التأخير التي تؤثر في حركة الطوابير ووقت الموظفين." }, { heading: "المنهج", detail: "طبّق العمل منهج DMAIC ورسم تدفق القيمة لتعريف المشكلة التشغيلية، وتحديد نقاط التسليم والاختناقات، وقياس التدفق القائم، وصياغة فرص تحسين موجهة." }, { heading: "النتيجة التي أفاد بها مالك الموقع", detail: "يفيد مالك الموقع بتحقيق خفض بنسبة 41% في وقت العملية وانخفاض بنسبة 50% في حجم الطوابير لمسار العمل المدروس. وهذه أرقام خاصة بالمشروع وليست وعداً بنتيجة قابلة للتكرار." }, { heading: "ما الذي يمكن نقله", detail: "الدرس المرتبط بالأتمتة هو إظهار نقاط التسليم غير المرئية، وحصر التدفق في الخطوات الضرورية، وقياس النتائج قبل توسيع أي عملية." }] },
    sample: { kicker: "نموذج توضيحي للتسليم", title: "ما الذي صُمم تحديث الحملة لعرضه.", intro: "هذا نموذج توضيحي لتقرير أسبوعي، وليس سجلاً لحملة حية ولا وعداً بحجم معين أو نتيجة أو استجابة من صاحب عمل.", reviewNote: "للتوضيح فقط — لا تمثل أي بيانات مرشح أو جهة عمل أو وظيفة أو تقديم أو نتيجة هنا بيانات حملة حية.", sections: [{ heading: "وتيرة التسليم", detail: "ينبغي أن تحدد خطة الحملة المكتوبة وتيرة التقرير المتفق عليها، مثل تحديث أسبوعي، وطريقة التواصل للأسئلة أو طلب الإيقاف." }, { heading: "حقول سجل التقديم", detail: "عند إرسال طلب فعلي، صُمم السجل الظاهر للمرشح لعرض جهة العمل والوظيفة والقناة وتاريخ الإرسال والحالة الحالية، مع التمييز بين المرسل والمعلّق والمتجاوز وأي رد مستلم." }, { heading: "ما لا يثبته التقرير", detail: "لا يضمن التقرير أن الوظيفة ما زالت مفتوحة أو أن صاحب العمل راجع الطلب أو أن مقابلة أو عرضاً سيتبع. تعكس الحالة الأدلة المتاحة وقت التحديث." }, { heading: "المعاينة مقابل الحملة الحية", detail: "أدوات الجاهزية والأمثلة في الموقع هي معاينات. تبدأ الحملة الحية فقط بعد خطة مكتوبة تحدد عائلات الأدوار والمواقع والقنوات والحد الأقصى والمدة وتفويض المرشح." }] },
  },
};

const PUBLIC_EMAIL = "apply@hsndm.tech";

const normalizePublicContact = (value: string) => value.replaceAll("hasan@hsndm.tech", PUBLIC_EMAIL);

function publicLegalContent(language: "en" | "ar", kind: PageKind): PageCopy {
  const source = copy[language][kind];
  if (kind === "privacy" && language === "en") {
    return {
      ...source,
      intro: "This Privacy Policy explains how AutoApply SA, a Jeddah-based service, handles personal information for Saudi job-search campaign support.",
      reviewNote: undefined,
      sections: [
        { heading: "Who is responsible", detail: "AutoApply SA is a Jeddah-based service. This page does not claim a separate legal entity name, registration number, or certification." },
        { heading: "Information we may collect", detail: "We may collect CVs or CV text you choose to share, contact details, target-role preferences, preferred language, city, campaign communications, enquiry information, and technical consent preferences. We aim to collect only what is relevant to the service you request." },
        { heading: "Why we use it", detail: "We use this information to assess fit, prepare or review a campaign plan, communicate with you, provide the agreed service, maintain your candidate dashboard, and protect the service." },
        { heading: "Sharing and campaign approval", detail: "We do not sell candidate information as a separate product. We may use service providers and channels needed to operate the service, such as hosting, authenticated dashboard, email, WhatsApp, and application platforms. Candidate information is shared with an employer or application channel only after the candidate approves the campaign direction." },
        { heading: "Retention and security", detail: "We keep identifiable information only as long as necessary for the agreed service, legal obligations, or documented disputes. We use organisational, administrative, and technical safeguards appropriate to the service, then delete or anonymise information when it is no longer needed." },
        { heading: "Your rights and contact", detail: "You can request access, correction, or deletion of your personal information by emailing apply@hsndm.tech or using the published WhatsApp channel. We may need to verify your identity before acting on a request." },
        { heading: "Cookies and optional analytics", detail: "Necessary storage records your privacy choice. Optional analytics remains off unless you allow it in the consent notice. You can reopen Cookie settings from the site at any time." },
      ],
    };
  }
  if (kind === "privacy" && language === "ar") {
    return {
      ...source,
      intro: "توضح سياسة الخصوصية هذه كيفية تعامل AutoApply SA، وهي خدمة مقرها جدة، مع المعلومات الشخصية لدعم حملات البحث عن عمل داخل السعودية.",
      reviewNote: undefined,
      sections: [
        { heading: "الجهة المسؤولة", detail: "AutoApply SA خدمة مقرها جدة. لا تدّعي هذه الصفحة وجود اسم كيان قانوني منفصل أو رقم تسجيل أو شهادة امتثال." },
        { heading: "المعلومات التي قد نجمعها", detail: "قد نجمع السيرة الذاتية أو نصها الذي تختار مشاركته وبيانات التواصل وتفضيلات الوظائف واللغة والمدينة ومراسلات الحملة ومعلومات الاستفسار وتفضيلات الموافقة التقنية. ونسعى إلى جمع ما يرتبط بالخدمة التي تطلبها فقط." },
        { heading: "سبب استخدامنا للمعلومات", detail: "نستخدم هذه المعلومات لتقييم الملاءمة وإعداد أو مراجعة خطة الحملة والتواصل معك وتقديم الخدمة المتفق عليها وإدارة لوحة المرشح وحماية الخدمة." },
        { heading: "المشاركة واعتماد الحملة", detail: "لا نبيع معلومات المرشحين كمنتج مستقل. وقد نستخدم مزودي خدمات وقنوات لازمة لتشغيل الخدمة مثل الاستضافة واللوحة الموثقة والبريد وWhatsApp ومنصات التقديم. ولا تُشارك معلومات المرشح مع صاحب عمل أو قناة تقديم إلا بعد اعتماد المرشح لاتجاه الحملة." },
        { heading: "الاحتفاظ والأمان", detail: "نحتفظ بالمعلومات القابلة للتعريف فقط للمدة اللازمة للخدمة المتفق عليها أو للالتزامات النظامية أو للنزاعات الموثقة. ونستخدم ضمانات تنظيمية وإدارية وتقنية مناسبة للخدمة، ثم نحذف المعلومات أو نُخفي هويتها عند انتهاء الحاجة إليها." },
        { heading: "حقوقك والتواصل", detail: "يمكنك طلب الوصول إلى معلوماتك الشخصية أو تصحيحها أو حذفها عبر البريد apply@hsndm.tech أو قناة WhatsApp المنشورة. وقد نحتاج إلى التحقق من هويتك قبل تنفيذ الطلب." },
        { heading: "ملفات الارتباط والتحليلات الاختيارية", detail: "يُستخدم التخزين الضروري لتسجيل اختيارك للخصوصية. وتبقى التحليلات الاختيارية معطلة ما لم تسمح بها في إشعار الموافقة. ويمكنك إعادة فتح إعدادات ملفات الارتباط في أي وقت." },
      ],
    };
  }
  if (kind === "terms") {
    return {
      ...source,
      intro: language === "ar" ? "توضح هذه الشروط موقع AutoApply SA وأدوات المعاينة وخدمة الحملة المتفق عليها. ولا تحل محل عرض سعر أو اتفاق حملة مكتوب منفصل." : "These terms explain the AutoApply SA website, preview tools, and agreed campaign service. They do not replace a separate written campaign quotation or agreement.",
      reviewNote: undefined,
    };
  }
  return source;
}

export default function InformationPage({ kind, language = "en" }: { kind: PageKind; language?: "en" | "ar" }) {
  const sourceContent = publicLegalContent(language, kind);
  const content = {
    ...sourceContent,
    sections: sourceContent.sections.map(section => ({ ...section, detail: normalizePublicContact(section.detail) })),
  };
  const root = language === "ar" ? "/ar" : "/";
  const routeName = kind === "how" ? "how-it-works" : kind === "case" ? "case-studies" : kind === "sample" ? "campaign-report-sample" : kind;
  const path = `${language === "ar" ? "/ar" : ""}/${routeName}`;
  const seoTitle = kind === "how"
    ? (language === "ar" ? "كيف تعمل أوتوأبلاي السعودية | البحث عن عمل" : "How AutoApply SA Works | Saudi Job Search")
    : kind === "support"
      ? (language === "ar" ? "دعم حملات التقديم في السعودية | AutoApply SA" : "Saudi Job Campaign Support | AutoApply SA")
      : `${content.title} | AutoApply SA`;
  useEffect(() => { applyPageSeo({ title: seoTitle, description: content.intro, path }); }, [content.intro, path, seoTitle]);
  return <InformationPageLayout content={content} language={language} root={root} />;
}
