import { ArrowLeft, ArrowUpRight, Check, MessageCircle, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useEffect } from "react";
import { applyPageSeo } from "@/lib/seo";

type PageKind = "how" | "support" | "privacy" | "terms";
const copy: Record<"en" | "ar", Record<PageKind, { kicker: string; title: string; intro: string; sections: [string, string][] }>> = {
  en: {
    how: { kicker: "HOW AUTOAPPLY SA WORKS", title: "A clear system for a Saudi job search.", intro: "We turn your role preferences and CV signals into a practical campaign conversation. Nothing is submitted from this page without your confirmation.", sections: [["1. Set your direction", "Choose Saudi cities, industries, language and role priorities."], ["2. Review the match", "Use the local CV check and AI ATS review to improve clarity before sharing a campaign brief."], ["3. Confirm your campaign", "WhatsApp opens with a prefilled summary so you decide what to send and attach."], ["4. Track progress", "Signed-in candidates can review their own submitted applications in the dashboard."]] },
    support: { kicker: "SUPPORT", title: "Help, without a ticket maze.", intro: "For campaign questions, use the WhatsApp handoff from your brief. For account and privacy requests, include the email you used in your campaign.", sections: [["Campaign support", "Use WhatsApp for the quickest conversation about a role target, CV attachment, or campaign status."], ["Dashboard access", "Sign in with the same account used for your candidate profile to view your personal application feed."], ["Privacy request", "Ask to access or remove campaign information by sending a clear request with your email address."], ["Response expectation", "If you do not receive a reply within one business day, send a concise WhatsApp follow-up."]] },
    privacy: { kicker: "PRIVACY", title: "Your search data should stay purposeful.", intro: "AutoApply SA is Saudi-focused. We aim to collect only the information needed to discuss and operate a job-application campaign.", sections: [["CV handling", "Local matching and ATS extraction happen in your browser. A CV file is not uploaded from the preview; only text you expressly submit for an AI ATS review is sent for that review."], ["Campaign briefs", "Names, contact details, target preferences and voluntary brief details may be used to respond to your campaign enquiry."], ["Your choices", "You may ask for access, correction, or deletion of campaign information by contacting us through the published support channel."], ["No sale of CV data", "We do not sell CVs or campaign brief details as a separate product."]] },
    terms: { kicker: "TERMS OF USE", title: "A practical agreement for the campaign journey.", intro: "These plain-language terms describe the preview, matching, campaign inquiry, and dashboard experience offered by AutoApply SA.", sections: [["Preview only", "Role matching and ATS results are guidance; they are not a promise of interviews, offers, or placement."], ["Your information", "You are responsible for the accuracy of the information and documents you choose to share."], ["No automatic submission from previews", "A campaign starts only after a separate conversation and your confirmation; submitting a web brief alone does not send job applications."], ["Service changes", "Features and availability may evolve as the service develops. Continued use means you accept the current version of these terms."]] },
  },
  ar: {
    how: { kicker: "كيف تعمل أوتوأبلاي السعودية", title: "نظام واضح لبحثك عن عمل داخل السعودية.", intro: "نحوّل تفضيلاتك وإشارات سيرتك الذاتية إلى ملخص حملة عملي. لا يُرسل أي طلب تقديم من هذه الصفحة دون تأكيدك.", sections: [["1. حدّد اتجاهك", "اختر المدن السعودية والمجالات واللغة وأولوية الوظيفة."], ["2. راجع المطابقة", "استخدم فحص السيرة المحلي ومراجعة ATS لتحسين الوضوح قبل مشاركة ملخص الحملة."], ["3. أكّد حملتك", "يفتح WhatsApp بملخص جاهز لتقرر أنت ما الذي سترسله وما الذي سترفقه."], ["4. تابع التقدم", "يمكن للمرشحين المسجلين مراجعة طلباتهم الخاصة داخل لوحة التحكم."]] },
    support: { kicker: "الدعم", title: "مساعدة واضحة بلا تعقيد.", intro: "لأسئلة الحملة، استخدم تحويل WhatsApp من ملخصك. ولطلبات الحساب والخصوصية، أرفق البريد المستخدم في الحملة.", sections: [["دعم الحملة", "استخدم WhatsApp لبدء محادثة سريعة حول الوظيفة المستهدفة أو السيرة أو حالة الحملة."], ["الوصول إلى اللوحة", "سجّل الدخول بالحساب نفسه المستخدم في ملفك لمراجعة تغذية طلباتك الشخصية."], ["طلب الخصوصية", "اطلب الوصول إلى معلومات حملتك أو حذفها بإرسال طلب واضح يتضمن بريدك الإلكتروني."], ["توقع الرد", "إذا لم يصلك رد خلال يوم عمل واحد، أرسل متابعة مختصرة عبر WhatsApp."]] },
    privacy: { kicker: "الخصوصية", title: "يجب أن تبقى بيانات بحثك عن عمل هادفة.", intro: "تخدم AutoApply SA الباحثين عن عمل داخل السعودية، ونسعى لجمع المعلومات اللازمة فقط لمناقشة وتشغيل حملة التقديم.", sections: [["التعامل مع السيرة", "تتم المطابقة المحلية واستخراج النص داخل متصفحك. لا يُرفع ملف السيرة من المعاينة؛ ولا يُرسل للتحليل إلا النص الذي تختار صراحة إرساله لمراجعة ATS."], ["ملخصات الحملة", "يمكن استخدام الاسم وبيانات الاتصال والتفضيلات وتفاصيل الملخص الطوعية للرد على استفسار حملتك."], ["اختياراتك", "يمكنك طلب الوصول إلى معلومات الحملة أو تصحيحها أو حذفها عبر قناة الدعم المنشورة."], ["عدم بيع البيانات", "لا نبيع السير الذاتية أو تفاصيل ملخصات الحملات كمنتج مستقل."]] },
    terms: { kicker: "شروط الاستخدام", title: "اتفاق عملي لمسار حملتك.", intro: "توضح هذه الشروط المبسطة تجربة المعاينة والمطابقة واستفسار الحملة ولوحة التحكم في AutoApply SA.", sections: [["المعاينة للإرشاد", "نتائج المطابقة وATS إرشادية ولا تمثل وعداً بمقابلة أو عرض أو توظيف."], ["معلوماتك", "أنت مسؤول عن دقة المعلومات والوثائق التي تختار مشاركتها."], ["لا إرسال تلقائياً من المعاينة", "لا تبدأ الحملة إلا بعد محادثة منفصلة وتأكيدك؛ وإرسال ملخص الويب وحده لا يرسل طلبات توظيف."], ["تطور الخدمة", "قد تتغير الميزات والإتاحة مع تطور الخدمة. استمرار الاستخدام يعني قبول النسخة الحالية من هذه الشروط."]] },
  },
};

export default function InformationPage({ kind, language = "en" }: { kind: PageKind; language?: "en" | "ar" }) {
  const content = copy[language][kind]; const root = language === "ar" ? "/ar" : "/"; const path = `${language === "ar" ? "/ar" : ""}/${kind === "how" ? "how-it-works" : kind}`;
  useEffect(() => { applyPageSeo({ title: `${content.title} | AutoApply SA`, description: content.intro, path }); }, [content, path]);
  return <main className="min-h-screen bg-[#f3f0e9] text-[#151515]" lang={language === "ar" ? "ar" : "en"} dir={language === "ar" ? "rtl" : "ltr"}><header className="border-b border-black/10 bg-[#fbf9f5]"><div className="page-frame py-5 flex items-center justify-between"><Link href={root} className="font-bold">AutoApply <em className="text-[#e5482a]">SA</em></Link><Link href={root} className="font-mono text-xs flex items-center gap-1">{language === "ar" ? "العودة للرئيسية" : "BACK TO HOME"}<ArrowLeft size={14}/></Link></div></header><section className="page-frame py-16 max-w-4xl"><p className="font-mono text-xs text-[#e5482a]">{content.kicker}</p><h1 className="mt-4 text-4xl md:text-6xl font-bold tracking-tight">{content.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-black/70">{content.intro}</p><div className="mt-12 grid gap-5 md:grid-cols-2">{content.sections.map(([heading, detail], index) => <article key={heading} className="border border-black/10 bg-white p-6"><span className="font-mono text-xs text-[#e5482a]">0{index + 1}</span><h2 className="mt-3 text-xl font-bold">{heading}</h2><p className="mt-3 leading-7 text-black/70">{detail}</p></article>)}</div><div className="mt-12 border border-black/10 bg-[#151515] text-white p-7 flex flex-col md:flex-row gap-5 items-start md:items-center justify-between"><div><div className="flex items-center gap-2 text-sm"><ShieldCheck size={17} className="text-[#e5482a]"/><b>{language === "ar" ? "خطوتك التالية تبقى بيدك" : "Your next step remains yours"}</b></div><p className="mt-2 text-sm text-white/70">{language === "ar" ? "ابدأ بملخص واضح، ثم أكّد ما تريد إرساله." : "Start with a clear brief, then confirm what you want to send."}</p></div><Link href={language === "ar" ? "/ar/enquire" : "/enquire"} className="bg-[#f3f0e9] text-[#151515] px-5 py-3 font-mono text-xs flex gap-2 items-center">{language === "ar" ? "ابدأ الحملة" : "START A CAMPAIGN"}<ArrowUpRight size={15}/></Link></div></section></main>;
}
