import { Check, MessageCircle, ShieldCheck } from "lucide-react";
import { Link } from "wouter";
import { useEffect } from "react";
import { applyPageSeo } from "@/lib/seo";

const plans = [
  { name: "Starter", price: "99", en: "A focused starting lane.", ar: "مسار بداية مركّز.", features: ["~40 applications", "Email + portal submit", "Weekly report"], featuresAr: ["نحو 40 طلب تقديم", "تقديم عبر البريد والمنصات", "تقرير أسبوعي"] },
  { name: "Pro", price: "149", en: "For active multi-channel momentum.", ar: "لزخم نشط عبر قنوات متعددة.", features: ["~90 applications", "Priority tailoring", "Daily report"], featuresAr: ["نحو 90 طلب تقديم", "تخصيص بأولوية", "تقرير يومي"], featured: true },
  { name: "Founder", price: "249", en: "High-touch targeting for a pivotal move.", ar: "استهداف عالي المتابعة لخطوة محورية.", features: ["~150 applications", "Multi-role targeting", "White-glove onboarding"], featuresAr: ["نحو 150 طلب تقديم", "استهداف أدوار متعددة", "تهيئة شخصية"] },
];

export default function PricingPage({ language = "en" }: { language?: "en" | "ar" }) {
  const arabic = language === "ar"; const root = arabic ? "/ar" : "/"; const enquiry = arabic ? "/ar/enquire" : "/enquire";
  const title = arabic ? "خطط واضحة لحملة التقديم." : "Clear options for your campaign.";
  const description = arabic ? "هذه أسعار إرشادية لحملات التقديم داخل السعودية. لا يتم تحصيل أي دفعة من هذه الصفحة." : "These are provisional Saudi application-campaign prices. This page does not collect a payment.";
  useEffect(() => { applyPageSeo({ title: `${arabic ? "الأسعار" : "Pricing"} | AutoApply SA`, description, path: arabic ? "/ar/pricing" : "/pricing" }); }, [arabic, description]);
  return <main className="min-h-screen bg-[#f3f0e9] text-[#151515]" dir={arabic ? "rtl" : "ltr"} lang={language}><header className="border-b border-black/10 bg-[#fbf9f5]"><div className="page-frame py-5 flex justify-between items-center"><Link href={root} className="font-bold">AutoApply <em className="text-[#e5482a]">SA</em></Link><Link href={root} className="font-mono text-xs">{arabic ? "العودة للرئيسية" : "BACK TO HOME"}</Link></div></header><section className="page-frame py-16"><p className="font-mono text-xs text-[#e5482a]">{arabic ? "خطط الحملة / ريال سعودي" : "CAMPAIGN PLANS / SAR"}</p><h1 className="mt-4 max-w-3xl text-4xl md:text-6xl font-bold tracking-tight">{title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-black/70">{description}</p><div className="mt-5 flex gap-2 items-center text-sm"><ShieldCheck size={17} className="text-[#e5482a]"/><span>{arabic ? "تبدأ الخطوة التالية بمحادثة وتأكيد منك." : "The next step starts with a conversation and your confirmation."}</span></div><div className="mt-12 grid gap-5 lg:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`border p-7 ${plan.featured ? "border-[#e5482a] bg-[#151515] text-white" : "border-black/10 bg-white"}`}><div className="flex justify-between font-mono text-xs"><span>{plan.name}</span>{plan.featured && <span className="text-[#e5482a]">{arabic ? "الأكثر اختياراً" : "MOST SELECTED"}</span>}</div><div className="mt-6 flex items-end gap-2"><strong className="text-5xl">{plan.price}</strong><span className="font-mono text-xs">SAR<br />{arabic ? "/ شهرياً" : "/ MO"}</span></div><p className="mt-5 min-h-12 text-sm opacity-75">{arabic ? plan.ar : plan.en}</p><ul className="mt-6 space-y-3 text-sm">{(arabic ? plan.featuresAr : plan.features).map(feature => <li key={feature} className="flex gap-2"><Check size={16} className="text-[#e5482a] shrink-0"/>{feature}</li>)}</ul><Link href={enquiry} className={`mt-8 inline-flex items-center gap-2 px-4 py-3 font-mono text-xs ${plan.featured ? "bg-[#f3f0e9] text-[#151515]" : "bg-[#151515] text-white"}`}><MessageCircle size={15}/>{arabic ? "ناقش هذه الخطة" : "DISCUSS THIS PLAN"}</Link></article>)}</div><p className="mt-8 max-w-3xl text-sm text-black/60">{arabic ? "لا تمثل هذه الصفحة بوابة دفع أو فاتورة. التغطية والنطاق النهائي وأي ترتيبات دفع تُؤكد في محادثة منفصلة قبل بدء أي حملة." : "This page is not a checkout or invoice. Final scope, coverage, and any payment arrangement are confirmed in a separate conversation before a campaign begins."}</p></section></main>;
}
