import { ArrowUpRight, Check, MessageCircle } from "lucide-react";
import { useEffect } from "react";
import { Link } from "wouter";
import { applyPageSeo } from "@/lib/seo";

const whatsapp = "966571448656";

export default function ServicesPage({ language = "en" }: { language?: "en" | "ar" }) {
  const arabic = language === "ar";
  const root = arabic ? "/ar" : "/";
  const copy = arabic ? {
    kicker: "مسارات العمل", title: "خدمتان مترابطتان، بأهداف واضحة.", intro: "AutoApply SA: دعم لحملات التقديم للوظائف في السعودية وأنظمة ويب عملية للشركات الصغيرة في جدة.", founder: "مهندس صناعي واستراتيجي أتمتة يركز على تبسيط العمليات وبناء أدوات عملية قابلة للقياس.", tracks: [
      { title: "AutoApply SA", label: "للباحثين عن عمل", detail: "دعم موجّه للسعودية لمطابقة المسار ومراجعة ATS ومحادثة حملة التقديم ولوحة متابعة المرشح.", points: ["بدء محلي من السيرة الذاتية", "لا إرسال قبل التأكيد", "متابعة مرئية للطلبات المتفق عليها"], action: "ابدأ نقاش الحملة", href: "/ar/enquire" },
      { title: "أنظمة الويب والتشغيل", label: "للشركات الصغيرة", detail: "مسار منفصل لبناء صفحة مبيعات أو موقع أعمال أو نموذج حجز والتقاط العملاء مع إدارة بسيطة قابلة للنمو.", points: ["موقع من صفحة واحدة أو حتى 5 صفحات", "نموذج تواصل وحجز ومتابعة العملاء", "نطاق واضح قبل البدء"], action: "ناقش مشروع موقع", href: `https://wa.me/${whatsapp}?text=${encodeURIComponent("مرحباً، أود مناقشة موقع أو نظام تشغيل لنشاطي في السعودية.")}` },
    ], note: "تبدأ المشاريع الرقمية المخصصة عادةً من نطاق متفق عليه، ويُناقش السعر النهائي قبل بدء العمل. لا تُجمع مدفوعات من هذه الصفحة.", cta: "استكشف دراسة الحالة",
  } : {
    kicker: "WORK TRACKS", title: "Two connected services, with clear outcomes.", intro: "AutoApply SA — Saudi-focused job-application campaign support and practical web systems for small businesses in Jeddah.", founder: "An industrial engineer and automation strategist focused on simplifying operations and building measurable, practical tools.", tracks: [
      { title: "AutoApply SA", label: "For job seekers", detail: "Saudi-focused support for career matching, ATS review, campaign discussion, and visible candidate application tracking.", points: ["CV-led local starting point", "No submission before confirmation", "Visible tracking for agreed activity"], action: "Start a campaign discussion", href: "/enquire" },
      { title: "Web & operations systems", label: "For small businesses", detail: "A separate path for a sales page, business website, booking flow, and lead capture that can grow into a simple operating system.", points: ["One-page site through five-page build", "Contact, booking, and lead follow-up", "Clear scope before work begins"], action: "Discuss a website project", href: `https://wa.me/${whatsapp}?text=${encodeURIComponent("Hi, I would like to discuss a website or operations system for my Saudi business.")}` },
    ], note: "Custom digital projects begin with an agreed scope; final price and delivery terms are discussed before work starts. This page does not collect payment.", cta: "Explore the case study",
  };
  useEffect(() => { applyPageSeo({ title: `${arabic ? "الخدمات" : "Services"} | AutoApply SA`, description: copy.intro, path: arabic ? "/ar/services" : "/services" }); }, [arabic, copy.intro]);

  return <main className="min-h-screen bg-[#f3f0e9] text-[#151515]" dir={arabic ? "rtl" : "ltr"} lang={language}><header className="border-b border-black/10 bg-[#fbf9f5]"><div className="page-frame flex items-center justify-between py-5"><Link href={root} className="font-bold">AutoApply <em className="text-[#e5482a]">SA</em></Link><Link href={root} className="font-mono text-xs">{arabic ? "العودة للرئيسية" : "BACK TO HOME"}</Link></div></header><section className="page-frame py-16"><p className="font-mono text-xs text-[#e5482a]">{copy.kicker}</p><h1 className="mt-4 max-w-4xl text-4xl font-bold tracking-tight md:text-6xl">{copy.title}</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-black/70">{copy.intro}</p><p className="mt-5 max-w-2xl border-s-4 border-[#e5482a] bg-white p-4 text-sm leading-6 text-black/75">{copy.founder}</p><div className="mt-12 grid gap-5 lg:grid-cols-2">{copy.tracks.map((track) => <article key={track.title} className="border border-black/10 bg-white p-7"><p className="font-mono text-xs text-[#e5482a]">{track.label}</p><h2 className="mt-3 text-3xl font-bold">{track.title}</h2><p className="mt-4 min-h-20 leading-7 text-black/70">{track.detail}</p><ul className="mt-6 space-y-3 text-sm">{track.points.map((point) => <li key={point} className="flex gap-2"><Check size={16} className="shrink-0 text-[#e5482a]" />{point}</li>)}</ul>{track.href.startsWith("http") ? <a href={track.href} className="mt-8 inline-flex items-center gap-2 bg-[#151515] px-4 py-3 font-mono text-xs" style={{ color: "#fff" }} target="_blank" rel="noreferrer"><MessageCircle size={15} />{track.action}</a> : <Link href={track.href} className="mt-8 inline-flex items-center gap-2 bg-[#151515] px-4 py-3 font-mono text-xs" style={{ color: "#fff" }}><ArrowUpRight size={15} />{track.action}</Link>}</article>)}</div><p className="mt-8 max-w-3xl text-sm leading-6 text-black/60">{copy.note}</p><Link href={arabic ? "/ar/case-studies" : "/case-studies"} className="mt-8 inline-flex items-center gap-2 border border-black/20 px-4 py-3 font-mono text-xs text-[#151515]"><ArrowUpRight size={15} />{copy.cta}</Link></section></main>;
}
