import {useState,type FormEvent} from 'react';
import {Link,useLocation} from 'wouter';
import {ArrowRight,ShieldCheck} from 'lucide-react';
import {supabase,useSession} from './auth';
import {useLocale} from './locale';
export function AuthPage({mode}:{mode:'signin'|'signup'|'forgot'|'reset'}){const {t,path}=useLocale();const [,navigate]=useLocation();const {session}=useSession();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const title={signin:t('Welcome back.','مرحباً بعودتك.'),signup:t('Your next step starts here.','خطوتك القادمة تبدأ هنا.'),forgot:t('Reset your password.','استعد كلمة المرور.'),reset:t('Choose a new password.','اختر كلمة مرور جديدة.')};
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const data=new FormData(e.currentTarget);const email=String(data.get('email')||''),password=String(data.get('password')||'');setBusy(true);setMessage('');try{if(mode==='signup'){const r=await supabase.auth.signUp({email,password,options:{emailRedirectTo:location.origin+path('/auth/callback')}});if(r.error)throw r.error;if(r.data.session)navigate(path('/dashboard'));else setMessage(t('Check your email to verify your account, then sign in.','تحقّق من بريدك لتأكيد الحساب، ثم سجّل الدخول.'));}else if(mode==='signin'){const r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;navigate(path('/dashboard'));}else if(mode==='forgot'){const r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+path('/reset-password')});if(r.error)throw r.error;setMessage(t('If an account exists, a reset link will arrive by email.','إذا كان الحساب موجوداً فسيصلك رابط استعادة عبر البريد.'));}else{if(!session)throw Error();const r=await supabase.auth.updateUser({password});if(r.error)throw r.error;setMessage(t('Password updated. You can return to your dashboard.','تم تحديث كلمة المرور. يمكنك العودة إلى لوحة التحكم.'));}}catch{setMessage(t('We could not complete this request. Check your details or try again.','تعذّر إكمال الطلب. تحقّق من بياناتك أو حاول مجدداً.'));}finally{setBusy(false);}}
 async function google(){if(!supabase)return;setBusy(true);try{const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin+path('/auth/callback')}});if(error)throw error;}catch{setMessage(t('Google sign-in is unavailable. Try email sign-in.','تسجيل الدخول بحساب Google غير متاح. جرّب البريد الإلكتروني.'));setBusy(false);}}
 return <main className="auth-page wrap"><div className="auth-story"><span className="section-label">AUTOAPPLY SA</span><h1>{t('A little less searching.','بحث أكثر تنظيماً.')}<br/><em>{t('A lot more direction.','وخطوات أكثر وضوحاً.')}</em></h1><p>{t('Your experience, preferences and next steps. Together.','خبراتك وتفضيلاتك وخطواتك القادمة، معاً.')}</p><ShieldCheck size={46}/></div><div className="auth-card"><h2>{title[mode]}</h2>{!supabase&&<p className="notice" role="status">{t('Account service is not connected in this preview. You can still explore your CV on the home page.','خدمة الحسابات غير متصلة في هذه المعاينة. يمكنك استكشاف سيرتك من الصفحة الرئيسية.')}</p>}{(mode==='signin'||mode==='signup')&&<><button className="button google full" disabled={!supabase||busy} onClick={google}>Google · {t('Continue with Google','المتابعة بحساب Google')}</button><div className="divider">{t('or use your email','أو استخدم بريدك')}</div></>}<form onSubmit={submit}>{mode!=='reset'&&<label>{t('Email address','البريد الإلكتروني')}<input name="email" type="email" autoComplete="email" required dir="ltr" placeholder="you@example.com"/></label>}{mode!=='forgot'&&<label>{t('Password','كلمة المرور')}<input name="password" type="password" autoComplete={mode==='signin'?'current-password':'new-password'} minLength={8} required dir="ltr"/></label>}<button className="button full" disabled={busy||!supabase||(mode==='reset'&&!session)}>{busy?t('Please wait…','يرجى الانتظار…'):mode==='signin'?t('Sign in','تسجيل الدخول'):mode==='signup'?t('Create account','إنشاء حساب'):mode==='forgot'?t('Send reset link','إرسال رابط الاستعادة'):t('Update password','تحديث كلمة المرور')}<ArrowRight size={17}/></button></form><p role="status">{message}</p>{mode==='signin'&&<Link href={path('/forgot-password')}>{t('Forgot password?','نسيت كلمة المرور؟')}</Link>}<p className="auth-switch">{mode==='signup'?t('Already have an account?','لديك حساب؟'):t('New to AutoApply?','جديد في AutoApply؟')} <Link href={path(mode==='signup'?'/sign-in':'/sign-up')}>{mode==='signup'?t('Sign in','سجّل الدخول'):t('Create account','أنشئ حساباً')}</Link></p><Link href={path('/')}>{t('Back to home','العودة للرئيسية')}</Link></div></main>
}
