import {useEffect,useState,type FormEvent} from 'react';
import {Link,useLocation} from 'wouter';
import {ArrowRight,ShieldCheck} from 'lucide-react';
import {getAuthRedirectUrl,supabase,useSession} from './auth';
import {useLocale} from './locale';
import {trackEngagement} from '@/lib/analytics';
export function AuthPage({mode}:{mode:'signin'|'signup'|'forgot'|'reset'}){const {t,path,ar}=useLocale();const [,navigate]=useLocation();const {session,loading}=useSession();const [busy,setBusy]=useState(false),[message,setMessage]=useState('');const title={signin:t('Welcome back.','مرحباً بعودتك.'),signup:t('Your next step starts here.','خطوتك القادمة تبدأ هنا.'),forgot:t('Reset your password.','أعد تعيين كلمة المرور.'),reset:t('Choose a new password.','اختر كلمة مرور جديدة.')};
 useEffect(()=>{setMessage('');},[mode]);
 useEffect(()=>{if(session&&(mode==='signin'||mode==='signup'))navigate(path('/dashboard'));},[session,mode,navigate,path]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!supabase)return;const data=new FormData(e.currentTarget);const email=String(data.get('email')||''),password=String(data.get('password')||'');setBusy(true);setMessage('');trackEngagement('auth_submitted',{mode});try{if(mode==='signup'){const r=await supabase.auth.signUp({email,password,options:{emailRedirectTo:getAuthRedirectUrl(path('/auth/callback'))}});if(r.error)throw r.error;trackEngagement('auth_succeeded',{mode,requiresEmailVerification:!r.data.session});if(r.data.session)navigate(path('/dashboard'));else setMessage(t('Check your email to verify your account, then sign in.','تحقّق من بريدك لتأكيد الحساب، ثم سجّل الدخول.'));}else if(mode==='signin'){const r=await supabase.auth.signInWithPassword({email,password});if(r.error)throw r.error;trackEngagement('auth_succeeded',{mode});navigate(path('/dashboard'));}else if(mode==='forgot'){const r=await supabase.auth.resetPasswordForEmail(email,{redirectTo:getAuthRedirectUrl(path('/reset-password'))});if(r.error)throw r.error;trackEngagement('password_reset_requested');setMessage(t('If an account exists, a reset link will arrive by email.','إذا كان الحساب موجوداً فسيصلك رابط استعادة عبر البريد.'));}else{if(!session)throw Error();const r=await supabase.auth.updateUser({password});if(r.error)throw r.error;trackEngagement('password_updated');setMessage(t('Password updated. You can return to your dashboard.','تم تحديث كلمة المرور. يمكنك العودة إلى لوحة التحكم.'));}}catch{trackEngagement('auth_failed',{mode});setMessage(t('We could not complete this request. Check your details or try again.','تعذّر إكمال الطلب. تحقّق من بياناتك أو حاول مجدداً.'));}finally{setBusy(false);}}
 async function google(){if(!supabase)return;setBusy(true);trackEngagement('oauth_started',{provider:'google'});try{const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:getAuthRedirectUrl(path('/auth/callback'))}});if(error)throw error;}catch{trackEngagement('oauth_failed',{provider:'google'});setMessage(t('Google sign-in is unavailable. Try email sign-in.','تسجيل الدخول بحساب Google غير متاح. جرّب البريد الإلكتروني.'));setBusy(false);}}
 return <main className="auth-page wrap"><div className="auth-story"><span className="section-label">AUTOAPPLY SA</span><h1>{t('A little less searching.','بحث أكثر تنظيماً.')}<br/><em>{t('A lot more direction.','وخطوات أكثر وضوحاً.')}</em></h1><p>{t('Your experience, preferences and next steps. Together.','خبراتك وتفضيلاتك وخطواتك القادمة، معاً.')}</p><ShieldCheck size={46}/></div><div className="auth-card"><h2>{title[mode]}</h2>{!supabase&&<p className="notice" role="status">{t('Account service is not connected in this preview. You can still explore your CV on the home page.','خدمة الحسابات غير متصلة في هذه المعاينة. يمكنك استكشاف سيرتك من الصفحة الرئيسية.')}</p>}{(mode==='signin'||mode==='signup')&&<><button className="button google full" disabled={!supabase||busy} onClick={google}>Google · {t('Continue with Google','المتابعة بحساب Google')}</button><div className="divider">{t('or use your email','أو استخدم بريدك')}</div></>}{mode==='reset'&&!session&&<p className="notice" role="status">{loading?t('Checking your reset link…','جارٍ التحقق من رابط الاستعادة…'):t('This reset link is missing, expired or could not be verified. Request a new link to continue.','رابط الاستعادة مفقود أو منتهي الصلاحية أو تعذّر التحقق منه. اطلب رابطاً جديداً للمتابعة.')}{!loading&&<> <Link href={path('/forgot-password')}>{t('Request a new reset link','طلب رابط استعادة جديد')}</Link></>}</p>}<form onSubmit={submit}>{mode!=='reset'&&<label>{t('Email address','البريد الإلكتروني')}<input name="email" type="email" autoComplete="email" required dir="ltr" placeholder="you@example.com"/></label>}{mode!=='forgot'&&<label>{t('Password','كلمة المرور')}<input name="password" type="password" autoComplete={mode==='signin'?'current-password':'new-password'} minLength={mode==='signin'?undefined:8} required dir="ltr"/></label>}<button className="button full" disabled={busy||!supabase||(mode==='reset'&&!session)}>{busy?t('Please wait…','يرجى الانتظار…'):mode==='signin'?t('Sign in','تسجيل الدخول'):mode==='signup'?t('Create account','إنشاء حساب'):mode==='forgot'?t('Send reset link','إرسال رابط الاستعادة'):t('Update password','تحديث كلمة المرور')}<ArrowRight className={ar ? '-scale-x-100' : ''} size={17}/></button></form><p role="status">{message}</p>{mode==='reset'&&session&&<Link href={path('/dashboard')}>{t('Return to dashboard','العودة إلى لوحة التحكم')}</Link>}{mode==='signin'&&<Link href={path('/forgot-password')}>{t('Forgot password?','نسيت كلمة المرور؟')}</Link>}<p className="auth-switch">{mode==='signup'?t('Already have an account?','لديك حساب؟'):t('New to AutoApply?','جديد في AutoApply؟')} <Link href={path(mode==='signup'?'/sign-in':'/sign-up')}>{mode==='signup'?t('Sign in','سجّل الدخول'):t('Create account','أنشئ حساباً')}</Link></p><Link href={path('/')}>{t('Back to home','العودة للرئيسية')}</Link></div></main>
}
