import {useRef,useState} from 'react';
import {FileText,UploadCloud,CheckCircle2,Loader2,LockKeyhole} from 'lucide-react';
import {Link} from 'wouter';
import {useLocale} from './locale';
import {FIELD_MAP} from '@/lib/careerTaxonomy';
export type CvResult={name:string;skills:string[];roles:string[]};
function readDraft():CvResult|null {try {const data=JSON.parse(sessionStorage.getItem('autoapply-cv-draft')||'null');return data&&typeof data.name==='string'&&Array.isArray(data.skills)&&Array.isArray(data.roles)?data:null;}catch{return null;}}
export let cvDraft:CvResult|null=readDraft();
export function clearCvDraft(){cvDraft=null;try{sessionStorage.removeItem('autoapply-cv-draft');}catch{}}
export function CvUpload({onParsed}:{onParsed?:(r:CvResult)=>void}){
 const {t,path}=useLocale(),input=useRef<HTMLInputElement>(null);const [state,setState]=useState('idle'),[error,setError]=useState(''),[result,setResult]=useState<CvResult|null>(cvDraft);
 async function parse(file?:File){if(!file)return;setError('');if(!/\.(pdf|docx)$/i.test(file.name)||file.size>10*1024*1024){setError(t('Choose a PDF or DOCX under 10 MB.','اختر ملف PDF أو DOCX بحجم أقل من ١٠ ميجابايت.'));return;}
 setResult(null);setState('reading');try{const {readCvText}=await import('@/lib/careerMatcher');const text=await readCvText(file);if(!text)throw Error();const lower=text.toLowerCase();const matching=FIELD_MAP.map(f=>({...f,found:f.keywords.filter(k=>lower.includes(k))})).filter(f=>f.found.length>0).sort((a,b)=>b.found.length-a.found.length);const r={name:file.name,skills:Array.from(new Set(matching.flatMap(f=>f.found))).slice(0,8),roles:matching.slice(0,2).flatMap(f=>f.items.slice(0,1))};cvDraft=r;try{sessionStorage.setItem('autoapply-cv-draft',JSON.stringify(r));}catch{}setResult(r);onParsed?.(r);setState('done');}catch{setState('error');setError(t('We could not read this file. Try a text-based PDF or DOCX. Scanned images need OCR.','تعذّرت قراءة الملف. جرّب PDF نصياً أو DOCX. الملفات الممسوحة تحتاج إلى تحويل النص.'));}}
 return <div className="cv-card" id="upload"><span className="eyebrow">{t('YOUR NEXT STEP STARTS HERE','خطوتك القادمة تبدأ هنا')}</span><h2>{t('Start with your CV.','ابدأ بسيرتك الذاتية.')}</h2><p>{t('Find the skills already in your experience.','تعرّف على المهارات الموجودة في خبراتك.')}</p><input ref={input} type="file" accept=".pdf,.docx" hidden onChange={e=>parse(e.target.files?.[0])}/><button type="button" className="dropzone" disabled={state==='reading'} onClick={()=>input.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();if(state!=='reading')parse(e.dataTransfer.files[0]);}}>{state==='reading'?<Loader2 className="spin" size={32}/>:result?<CheckCircle2 size={32}/>:<UploadCloud size={32}/>}<strong>{state==='reading'?t('Reading your CV…','جارٍ قراءة سيرتك…'):result?result.name:t('Drop your CV here','اسحب سيرتك الذاتية هنا')}</strong><span>{t('or click to browse · PDF / DOCX · 10 MB','أو اضغط لاختيار الملف · PDF / DOCX · ١٠ ميجابايت')}</span></button><div role="status" aria-live="polite">{error&&<p className="error">{error}</p>}{result&&<div className="cv-result"><small>{t('Keywords found in your CV','كلمات مستخرجة من سيرتك')}</small><div className="chips">{result.skills.map(s=><span key={s}>{s}</span>)}</div><p>{result.roles.length?t('Roles to explore','مسميات تستحق البحث')+ ' · '+result.roles.join(' / '):t('Your text is readable. Add your target role in the next step.','النص مقروء. أضف المسمى المطلوب في الخطوة التالية.')}</p><small>{t('Keyword-based suggestions, not live job matches.','اقتراحات من كلمات السيرة، وليست وظائف شاغرة مؤكدة.')}</small></div>}</div>{!onParsed&&<Link className="button full" href={path('/sign-up')}>{result?t('Continue with your profile','تابع إعداد ملفك'):t('Start free','ابدأ مجاناً')}</Link>}<small className="privacy"><LockKeyhole size={14}/>{t('Text is read on your device. Your file is not uploaded.','تُقرأ السيرة على جهازك دون رفع الملف.')}</small></div>
}
