// @vitest-environment jsdom
import {describe,it,expect,vi,beforeEach,afterEach} from 'vitest';
import {render,screen,fireEvent,cleanup,waitFor} from '@testing-library/react';
import {Router} from 'wouter';
import {memoryLocation} from 'wouter/memory-location';
import {LocaleProvider} from './locale';
const mocks=vi.hoisted(()=>({data:{} as any,sendApplicationEmail:vi.fn()}));
vi.mock('./data',()=>({useWorkspaceData:()=>mocks.data,saudiWeekStart:()=>new Date('2026-09-19T21:00:00Z')}));
vi.mock('./auth',()=>({useSession:()=>({session:{user:{id:'test-user',email:'candidate@example.com'}}}),supabase:{auth:{signOut:vi.fn().mockResolvedValue({error:null})}}}));
vi.mock('./backend',()=>({useBackendHealth:()=>({data:{ok:true,status:200},isLoading:false}),useApplicationDeliveryReadiness:()=>({data:{ok:true,status:200},isLoading:false}),useRecommendedJobs:()=>({data:{jobs:[{id:'job-1',companyName:'Saudi Digital Bank',roleTitle:'Operations Analyst',city:'Riyadh',source:'LinkedIn',url:'https://example.com',summary:'',matchReason:'Based on your focus.',freshness:'now'}],mode:'curated',checkedAt:'2026-09-23T00:00:00Z'},isLoading:false,isError:false,refetch:vi.fn()}),sendApplicationEmail:mocks.sendApplicationEmail}));
import {Workspace} from './Workspace';
function mount(path='/dashboard'){const memory=memoryLocation({path});render(<Router hook={memory.hook}><LocaleProvider><Workspace/></LocaleProvider></Router>);return memory;}
beforeEach(()=>{mocks.sendApplicationEmail.mockReset();mocks.sendApplicationEmail.mockResolvedValue({ok:true,status:200,error:''});mocks.data={profile:{data:{fullName:'Test Candidate',targetCity:'Jeddah',targetIndustry:'Operations'},isSuccess:true},apps:{data:[],refetch:vi.fn()},create:{mutate:vi.fn()},update:{mutate:vi.fn()},saveProfile:{mutateAsync:vi.fn().mockResolvedValue(undefined)},claimAccess:{mutateAsync:vi.fn().mockResolvedValue({ok:true,applications:50,name:'Test Candidate'}),isPending:false},clear:vi.fn()};});
afterEach(cleanup);
describe('V2 workspace behavior',()=>{
 it('offers private candidate access before onboarding',async()=>{mocks.data.profile.data=null;mount();expect(await screen.findByRole('heading',{name:'Connect your application history.'})).toBeTruthy();expect(screen.getByRole('link',{name:'I am a new user without a code'})).toBeTruthy();});
 it('renders the real empty state without illustrative account records',()=>{mount();expect(screen.getByRole('heading',{name:'Your next opportunity starts here.'})).toBeTruthy();expect(screen.queryByText('Example company')).toBeNull();});
 it('shows a recoverable service error',()=>{mocks.data.profile.isError=true;mount();expect(screen.getByRole('button',{name:'Retry'})).toBeTruthy();expect(screen.queryByRole('button',{name:'Track a job'})).toBeNull();});
 it('submits only the entered job to the tracker adapter',()=>{mount();fireEvent.click(screen.getByRole('button',{name:'Track a job'}));fireEvent.change(screen.getByLabelText('Company'),{target:{value:'Test Company'}});fireEvent.change(screen.getByLabelText('Role'),{target:{value:'Engineer'}});fireEvent.click(screen.getByRole('button',{name:'Save job'}));expect(mocks.data.create.mutate).toHaveBeenCalledWith({companyName:'Test Company',roleTitle:'Engineer',city:'Riyadh'},expect.any(Object));});
 it('sends an application through the backend and records it as applied',async()=>{mount();fireEvent.change(screen.getByLabelText('Employer name'),{target:{value:'Hiring Co'}});fireEvent.change(screen.getByLabelText('Position title'),{target:{value:'Analyst'}});fireEvent.change(screen.getByLabelText('Recipient email'),{target:{value:'hiring@example.com'}});fireEvent.change(screen.getByLabelText('Application message'),{target:{value:'I am excited to apply because my experience is a strong match for this role.'}});fireEvent.click(screen.getByRole('button',{name:'Send and record application'}));await waitFor(()=>expect(mocks.sendApplicationEmail).toHaveBeenCalledWith(expect.objectContaining({toEmail:'hiring@example.com',companyName:'Hiring Co',roleTitle:'Analyst',candidateEmail:'candidate@example.com'})));expect(mocks.data.create.mutate).toHaveBeenCalledWith({companyName:'Hiring Co',roleTitle:'Analyst',city:'Jeddah',status:'applied'},expect.any(Object));});
 it('keeps form entries when profile saving fails',async()=>{mocks.data.saveProfile.mutateAsync.mockRejectedValue(Error('offline'));mount('/settings');fireEvent.change(screen.getByLabelText('Target role or field'),{target:{value:'Engineer'}});fireEvent.click(screen.getByRole('button',{name:'Save and open dashboard'}));await waitFor(()=>expect(screen.getByRole('alert').textContent).toContain('Could not save'));expect((screen.getByLabelText('Target role or field') as HTMLInputElement).value).toBe('Engineer');});
 it('distinguishes failure from an empty application list',()=>{mocks.data.apps.isError=true;mount();expect(screen.getByRole('alert').textContent).toContain('Applications could not be loaded');expect(screen.queryByText('Your next opportunity starts here.')).toBeNull();});
});
